# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
